<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class DemoCatalogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = collect([
            'fresh-aquatic' => [
                'name' => 'Fresh & Aquatic',
                'description' => 'Crisp, cooling fragrances with a clean modern trail.',
            ],
            'night-out' => [
                'name' => 'Night Out',
                'description' => 'Magnetic sweet scents made for evenings and occasions.',
            ],
            'warm-spiced' => [
                'name' => 'Warm & Spiced',
                'description' => 'Rich amber, woods, and spice with a confident presence.',
            ],
        ])->mapWithKeys(function (array $attributes, string $slug): array {
            $category = Category::updateOrCreate(['slug' => $slug], $attributes);

            return [$slug => $category];
        });

        $products = [
            [
                'slug' => 'armaf-venana',
                'category' => 'fresh-aquatic',
                'name' => 'Armaf Ventana',
                'brand' => 'Armaf',
                'image_path' => '/images/products/armaf-ventana.jpeg',
                'image_alt' => 'Armaf Ventana fragrance bottle in warm sunlight',
                'description' => 'A polished aromatic fragrance with bright citrus, clean herbs, and a confident woody finish.',
                'style' => 'Citrus, aromatic woods',
                'opening_smell' => 'Grapefruit, mandarin, and a cool herbal lift.',
                'main_vibe' => 'Clean, sharp, and composed.',
                'character' => 'Modern and easy to wear.',
                'overall_smell' => 'Fresh citrus moves into dry woods, amber, and a soft musky base.',
                'best_seasons' => 'Spring and Summer',
                'use_cases' => 'Work, Everyday, Casual Day Out',
                'longevity' => '6–8 hours on skin',
                'projection' => 'Fresh and noticeable for the first two hours.',
                'sku' => 'ARM-VEN-100',
                'price_cents' => 3600,
            ],
            [
                'slug' => 'afnan-9pm-night-out',
                'category' => 'night-out',
                'name' => 'Afnan 9PM Night Out',
                'brand' => 'Afnan',
                'image_path' => '/images/products/afnan-9pm-night-out.jpeg',
                'image_alt' => 'Afnan 9PM Night Out bottle and presentation box on black fabric',
                'description' => 'A playful after-dark scent with sparkling fruit, warm spice, and smooth vanilla.',
                'style' => 'Sweet vanilla and spice',
                'opening_smell' => 'Crisp apple, bergamot, and a dash of cinnamon.',
                'main_vibe' => 'Bold, social, and energetic.',
                'character' => 'Sweet with a confident edge.',
                'overall_smell' => 'Vanilla, amber, and tonka create a warm trail that lasts well into the night.',
                'best_seasons' => 'Autumn and Winter',
                'use_cases' => 'Night Out, Dates, Events',
                'longevity' => '8–10 hours on skin',
                'projection' => 'Strong for the first three hours.',
                'sku' => 'AFN-9PM-100',
                'price_cents' => 4200,
                'sale_price_cents' => 3900,
            ],
            [
                'slug' => 'lattafah-asad-elixir',
                'category' => 'warm-spiced',
                'name' => 'Lattafa Asad Elixir',
                'brand' => 'Lattafa',
                'image_path' => '/images/products/lattafa-asad-elixir.png',
                'image_alt' => 'Lattafa Asad Elixir black bottle beside its presentation box',
                'description' => 'Deep peppery spice, dark amber, and smooth vanilla for a rich signature with presence.',
                'style' => 'Spiced amber elixir',
                'opening_smell' => 'Black pepper, pineapple, and tobacco leaf.',
                'main_vibe' => 'Powerful, warm, and self-assured.',
                'character' => 'Dark spice with a smooth finish.',
                'overall_smell' => 'Coffee, iris, amber, vanilla, and dry woods settle into a dense evening scent.',
                'best_seasons' => 'Autumn and Winter',
                'use_cases' => 'Evenings, Formal Events, Signature Scent',
                'longevity' => '9–11 hours on skin',
                'projection' => 'Strong with a long, warm scent trail.',
                'sku' => 'LAT-ASAD-100',
                'price_cents' => 4500,
            ],
            [
                'slug' => 'havas-ice',
                'category' => 'fresh-aquatic',
                'name' => 'Rasasi Hawas Ice',
                'brand' => 'Rasasi',
                'image_path' => '/images/products/rasasi-hawas-ice.webp',
                'image_alt' => 'Blue Rasasi Hawas Ice bottle on an icy blue display',
                'description' => 'An icy aquatic scent with juicy citrus, crisp aromatics, and a clean mineral drydown.',
                'style' => 'Iced citrus and marine notes',
                'opening_smell' => 'Frozen lemon, lime, and bright green apple.',
                'main_vibe' => 'Cooling, lively, and effortless.',
                'character' => 'Sporty with a refined edge.',
                'overall_smell' => 'Marine air, lavender, musk, and pale woods leave a crisp clean trail.',
                'best_seasons' => 'Spring and Summer',
                'use_cases' => 'Gym, Daytime, Holidays, Everyday',
                'longevity' => '7–9 hours on skin',
                'projection' => 'Bright and fresh for the first two hours.',
                'sku' => 'HAV-ICE-100',
                'price_cents' => 3900,
            ],
            [
                'slug' => 'proud-of-you',
                'category' => 'night-out',
                'name' => 'Proud of You',
                'brand' => 'Fragrance World',
                'image_path' => '/images/products/fragrance-world-proud-of-you.jpg',
                'image_alt' => 'Fragrance World Proud of You amber fragrance bottle',
                'description' => 'A warm modern gourmand built around cinnamon, roasted chestnut, and addictive vanilla.',
                'style' => 'Warm gourmand woods',
                'opening_smell' => 'Cardamom, pink pepper, and fresh violet leaf.',
                'main_vibe' => 'Inviting, charismatic, and warm.',
                'character' => 'Smooth sweetness with depth.',
                'overall_smell' => 'Chestnut, vanilla, amberwood, and soft suede create a cosy drydown.',
                'best_seasons' => 'Autumn and Winter',
                'use_cases' => 'Date Night, Dinner, Celebrations',
                'longevity' => '8–10 hours on skin',
                'projection' => 'Strong at first, then a warm personal cloud.',
                'sku' => 'FW-PROUD-100',
                'price_cents' => 3800,
            ],
            [
                'slug' => 'havas-kobra',
                'category' => 'fresh-aquatic',
                'name' => 'Rasasi Hawas Kobra',
                'brand' => 'Rasasi',
                'image_path' => '/images/products/rasasi-hawas-kobra.png',
                'image_alt' => 'Dark Rasasi Hawas Kobra fragrance bottle',
                'description' => 'A vibrant green fragrance balancing tart fruit, aromatic spice, and sleek woody musk.',
                'style' => 'Green aromatic freshness',
                'opening_smell' => 'Bergamot, green apple, and cool mint.',
                'main_vibe' => 'Energetic, focused, and contemporary.',
                'character' => 'Fresh with a darker woody bite.',
                'overall_smell' => 'Aromatic herbs meet cedar, amber, and clean musk.',
                'best_seasons' => 'Spring, Summer, and Early Autumn',
                'use_cases' => 'Work, Travel, Everyday',
                'longevity' => '7–8 hours on skin',
                'projection' => 'Moderate and consistent.',
                'sku' => 'HAV-KOB-100',
                'price_cents' => 4100,
            ],
            [
                'slug' => 'velixir-orion',
                'category' => 'warm-spiced',
                'name' => 'Velixir Orion',
                'brand' => 'Velixir',
                'image_path' => '/images/products/velixir-orion-exact.jpg',
                'image_alt' => 'Velixir Orion amber bottle with its black and gold presentation boxes',
                'description' => 'Luminous spice and polished woods orbit a smooth amber core in this versatile signature.',
                'style' => 'Amber woods and bright spice',
                'opening_smell' => 'Bergamot, saffron, and cardamom.',
                'main_vibe' => 'Elegant, assured, and radiant.',
                'character' => 'Refined warmth for day or night.',
                'overall_smell' => 'Iris, cedar, amber, and vanilla create a smooth tailored finish.',
                'best_seasons' => 'Autumn, Winter, and Spring',
                'use_cases' => 'Work, Events, Signature Scent',
                'longevity' => '8–9 hours on skin',
                'projection' => 'Moderate with an elegant trail.',
                'sku' => 'VEL-ORI-100',
                'price_cents' => 5200,
            ],
            [
                'slug' => 'velixir-icarus',
                'category' => 'night-out',
                'name' => 'Velixir Icarus',
                'brand' => 'Velixir',
                'image_path' => '/images/products/velixir-icarus-exact.jpg',
                'image_alt' => 'Blue and gold Velixir Icarus fragrance bottle',
                'description' => 'A daring sweet-spiced fragrance with glowing fruit, smoked woods, and a plush vanilla base.',
                'style' => 'Smoked fruit and vanilla',
                'opening_smell' => 'Blood orange, plum, and warm pepper.',
                'main_vibe' => 'Expressive, daring, and magnetic.',
                'character' => 'Bright at first, dark at the edges.',
                'overall_smell' => 'Incense, sandalwood, tonka, and vanilla form a rich late-night trail.',
                'best_seasons' => 'Autumn and Winter',
                'use_cases' => 'Night Out, Parties, Creative Events',
                'longevity' => '9–11 hours on skin',
                'projection' => 'Strong and attention-grabbing.',
                'sku' => 'VEL-ICA-100',
                'price_cents' => 5400,
            ],
            [
                'slug' => 'lattafah-fakhar-black',
                'category' => 'warm-spiced',
                'name' => 'Lattafa Fakhar Black',
                'brand' => 'Lattafa',
                'image_path' => '/images/products/lattafa-fakhar-black.png',
                'image_alt' => 'Black and silver Lattafa Fakhar Black bottle beside its presentation box',
                'description' => 'A smooth aromatic fragrance blending fresh fruit, lavender, herbs, and warm tonka woods.',
                'style' => 'Aromatic tonka and woods',
                'opening_smell' => 'Apple, bergamot, and ginger.',
                'main_vibe' => 'Polished, versatile, and confident.',
                'character' => 'Fresh aromatics with a warm base.',
                'overall_smell' => 'Lavender, sage, juniper, tonka, amberwood, and cedar settle cleanly.',
                'best_seasons' => 'All Seasons',
                'use_cases' => 'Work, Dinner, Everyday, Signature Scent',
                'longevity' => '7–9 hours on skin',
                'projection' => 'Moderate with a clean aromatic trail.',
                'sku' => 'LAT-FAK-100',
                'price_cents' => 4000,
            ],
        ];

        foreach ($products as $productData) {
            $product = Product::updateOrCreate(
                ['slug' => $productData['slug']],
                [
                    'category_id' => $categories[$productData['category']]->id,
                    'name' => $productData['name'],
                    'brand' => $productData['brand'],
                    'description' => $productData['description'],
                    'style' => $productData['style'],
                    'opening_smell' => $productData['opening_smell'],
                    'main_vibe' => $productData['main_vibe'],
                    'character' => $productData['character'],
                    'overall_smell' => $productData['overall_smell'],
                    'best_seasons' => $productData['best_seasons'],
                    'use_cases' => $productData['use_cases'],
                    'longevity' => $productData['longevity'],
                    'projection' => $productData['projection'],
                    'image_path' => $productData['image_path'],
                    'image_alt' => $productData['image_alt'],
                    'gallery' => [],
                    'is_published' => true,
                ],
            );

            $product->variants()->updateOrCreate(
                ['sku' => $productData['sku']],
                [
                    'size' => '100 ml',
                    'currency' => 'USD',
                    'price_cents' => $productData['price_cents'],
                    'sale_price_cents' => $productData['sale_price_cents'] ?? null,
                    'stock_quantity' => 24,
                    'is_active' => true,
                ],
            );
        }
    }
}
